name: Build & deploy

on:
  push:
    paths:
      - './prototype/doctours-ui/**'
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # run this script in the frontend folder
    defaults:
      run:
        working-directory: prototype/doctors-ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      # we don't have tests
      # - name: Run tests
      #   run: yarn test

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./prototype/doctors-ui/build/
          if-no-files-found: error

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if:
      github.ref == 'refs/heads/main'

    # run this script in the frontend folder
    defaults:
      run:
        working-directory: prototype/doctors-ui

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./prototype/doctors-ui/build/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./prototype/doctors-ui/build/
